language: scala

sudo: false

matrix:
  include:
  - jdk: openjdk8
  - jdk: openjdk11
    dist: xenial

script:
  - sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test assembly

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"

before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
